### ISSUE TITLE
Grand unification of shells

### ISSUE THREAD

**Issue by fachat** [fachat/GeckOS-V2#4]
As taken from Glenn Holmer's commentary on https://www.youtube.com/watch?v=jtlAOdJmeDI&t=134s

Currently there are two shells - the old "shell" and the new "lsh". Not all functionality has been implemented in lsh yet, so shell keeps being around.
Extending lsh to completely take over from "shell" would allow to clean up the "shell" code, and allow to separate out the "mon" (which is currently mangled with the old shell) to be come a first class program on its own.

**Comment by fachat** [comment]
@Cenbe what are the exact functionalities that are missing?

- GETINFO -> "ps" is one.

**Comment by Cenbe** [comment]
Also a "kill" command that could send arbitrary signals like the Unix command does.

**Comment by fachat** [comment]
Another candidates (from here http://www.6502.org/users/andre/osa/shell.html ) are:
1) builtins:
`
COPYCON (like "<< EOF" shell redirection)
DUP (redirect current STDIO)
BATCH (like "source" shell command)`
2) externals:
`
DEVCMD
`

**Comment by fachat** [comment]
The let's add "MORE" here as well.

**Comment by fachat** [comment]
MORE is done, DUP as well.

**Comment by fachat** [comment]
input redirection can now be done using "<<" so that input to a command can be given via command line interface

**Comment by fachat** [comment]
source command is there now too

**Comment by fachat** [comment]
Either done or separated into own tickets - finally closing this one!
