### ISSUE TITLE
Re-test the inetd

### ISSUE THREAD

**Issue by fachat** [fachat/GeckOS-V2#43]
@Cenbe reported a bug when trying to setup the internet daemon. Can you pls add details here?

**Comment by Cenbe** [comment]
I sent a long email with packet traces and screenshots.

**Comment by fachat** [comment]
slipd now runs fine with the C64 9600 baud userport interface.
Still to test:
- telnet
- httpd

**Comment by fachat** [comment]
... and add a man page for it.
- let slipd use common.a65 cmdline parsing (e.g. "slipd -d a:ser1" 
- test builtin fstcp file system driver

**Comment by fachat** [comment]
This has been tested and re-tested in VICE and with a real C64 (C128 in C64 mode) with a UP9600 interface.
