### ISSUE TITLE
Documentation and README.md update suggestion

### ISSUE THREAD

**Issue by bitcoinmeetups** [fachat/GeckOS-V2#76]
Hi,

I'm Mr. Magnet, a very friendly guy. I like reading this source code, it's excellent. C64 assembly is beautiful and powerful. I have two suggestions for small improvements:

1. On the front page of this repo, near the top, please link to the the latest version of the d64 file. Don't use .gz because the file is tiny anyway and .gz needs gzip, tar -xvf doesn't work. And let's make it as easy for the end users as possible, no need to compress the file at all. It should be fun and quick to download for all c64 users.

2. Is it possible to go online through vice using your new internet features? If so please provide a short guide about how to telnet into a website using geckos + vice. That would be amazing and open up so many doors.

I'm very glad to see that this project is still active. It's one of the best I have seen for the c64. And the new internet features are so intriguing, I really want to test them. I don't have a physical device here though so I hope I can test through an emulator or other means.

**Comment by bitcoinmeetups** [comment]
If you want to talk about this project, please visit http://mywhatsapp.us.to

**Comment by fachat** [comment]
Thanks for the nice comments. Currently I do not have ready-made D64 images, but this is a good idea. I will only have to link multiple D64 images, one per port (C64, PET, CBM8x96, ...). I will have to think about making the build process efficient and that they are always up-to-date

Regarding internet access, it is actually not really new, just overhauled. Currently it works on the real hardware, where I am using hardware handshake to make sure no characters get lost. The VICE rs232 driver has some issues with that it seems. I looked at it and it still is on my TODO list to fix it (I wrote the ACIA and 9600baud userport emulation in VICE a looong time ago....) - I tried it but it requires some internal changes I will have to dig deeper into. So it may take its time.
But when this is fixed, yes, I did go to the internet with my C64.

**Comment by fachat** [comment]
I have replaced the userport 9600 baud implementation of the C64 architecture with support of an NMI-driven swiftlink device (to change back, change the C64 build).
With this I have successfully tested the internet connectivity and some of the programs (some still fail).
